apiVersion: v1
kind: Service
metadata:
  name: react-application
  labels:
    run: react-application
spec:
  type: LoadBalancer
  ports:
  - port: 8088
    targetPort: 8088
    protocol: TCP
    name: http
  selector:
    run: react-application
